---
title: "Medidas dasométricas"
author: "Cristian Gañan"
date: ""
output: 
  pdf_document:
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

library(tidyverse)
library(ggplot2)
library(readxl)
```


```{r}
data<- read.csv2("Salida1.csv")

data<- data %>% mutate(Parcela = as.factor(Parcela),
                       Subparcela = as.factor(Subparcela)) %>% select(-c(X.))


data<- data %>% group_by(Parcela) %>% mutate(`Area ind(m)`= (pi/4)*(DAP_cm/100)^2, 
                                             Dap_f_cm = (d1+d2)/2, 
                                             `Area copa(m)` = (pi/4)*(D_copa)^2) %>% 
  mutate(`Error DAP`= ((abs(Dap_f_cm - DAP_cm))/ DAP_cm)*100, 
         `Error alt` = ((abs(Alt_med - Alt_cal))/ Alt_cal)*100) 

data1<- data %>% rename(DAP_obs= DAP_cm, DAP_est= Dap_f_cm, 
                Alt_obs= Alt_cal, Alt_est= Alt_med) %>% select(DAP_obs, DAP_est, Alt_obs, Alt_est,
                                                                       `Error DAP`, `Error alt`) %>% 
  filter(DAP_est != "NA")
data1

data1 %>% group_by(Parcela)%>% summarise(DAP_obs= mean(DAP_obs), DAP_est= mean(DAP_obs), Alt_obs= mean(Alt_obs), Alt_est= mean(Alt_est), `Error DAP`= mean(`Error DAP`), `Error alt`= mean(`Error alt`))

```



```{r}
data %>% group_by(Subparcela) %>% 
  summarise(a= sum(`Area ind(m)`), 
            Dcm= sqrt(mean(DAP_cm^2)),
            Area_copa_p= sum(`Area copa(m)`)/length(Subparcela), 
            Altura_p= sum(Alt_cal)/length(Subparcela)) %>% 
  mutate(`Area basal`= a*10000/100) %>% 
  select(c(Subparcela, Dcm, `Area basal`, Area_copa_p, 
           Altura_p)) %>% slice(-c(1))

data %>% group_by(Parcela) %>% 
  summarise(a= sum(`Area ind(m)`), N_ind= length(Parcela),
            Dcm= sqrt(mean(DAP_cm^2))) %>% 
  mutate(`Area basal`= a*10000/250) %>% 
  select(c(Parcela, Dcm, `Area basal`))


```

## Distribuciónes DAP

```{r}

ggplot(data, mapping = aes(x= DAP_cm, col= "pink")) +
  geom_histogram(binwidth = 5, bins = 7) + labs(y= "Individuos")

```


## distribuciónes alt

```{r}
data1<- data %>% filter(Alt_cal != "NA")

ggplot(data, mapping = aes(x= Alt_cal, col= "pink")) +
  geom_histogram(binwidth = 3, bins = 5) + labs(y= "Individuos")

```


## distribuciones copa

```{r}
ggplot(data, mapping = aes(x= `Area copa(m)`, col= "pink")) +
  geom_histogram(binwidth = 10, bins = 7) + labs(y= "Individuos")
```

#Modelos

```{r}

data1<- read_xlsx("datoscampo.xlsx")
data1<- data1 %>% mutate(Parcela= as.factor(Parcela), 
                         Subparcela= as.factor(Subparcela))

data2<- read.csv("SantaElena1.csv")

data2<- data2 %>% mutate(Parcela= as.factor(Parcela)) %>% mutate(Altura=                                                                  dist_h_m*(tan(V_mas*pi/180)-tan(V_menos*pi/180)), 
                                                                 `Area copa(m)` = (pi/4)*(dcopa)^2)


  

```



