---
title: Analisis de variables climáticas parámo la Rusia

# Use letters for affiliations
author:
  - name: Camilo Andres Cruz Sanchez
    affiliation: a
  - name: Juan David Leon Torres
    affiliation: a
  - name: Juan Jose Olarte Zapata
    affiliation: a
  - name: Natali Andrea Lopez Toro
    affiliation: b
  - name: Cristian Camilo Gañan Tapasco
    affiliation: a
address:
  - code: a
    address: Departamento de ciencias forestales, Universidad Nacional de Colombia, Medellín
  - code: b
    address: Área curricular de Medio Ambiente , Universidad Nacional de Colombia, Medellín
    
# Optional: line of arbitrary text with additional information.
# Could be used, for example, to mention the bibliographic info in a post-print.
# If not specified, defaults to "This version was compiled on \today"
#date_subtitle: Published in *Journal of Statistical Software*, 2018

# For footer text  TODO(fold into template, allow free form two-authors)
lead_author_surname: Cruz; Leon; Olarte; Lopez; Gañan

# Place eg a DOI URL or CRAN Package URL here
doi_footer: "Hidrología Forestal"

# Abstract
abstract: |
  Your abstract will be typeset here, and used by default a visually distinctive font.
  An abstract should explain to the general reader the major contributions of the article. 

# Optional: Acknowledgements


# Optional: One or more keywords
keywords:
  - one
  - two
  - optional
  - keywords
  - here

# Paper size for the document, values of letter and a4
papersize: letter

# Font size of the document, values of 9pt (default), 10pt, 11pt and 12pt
fontsize: 9pt

# Optional: Force one-column layout, default is two-column
#one_column: true

# Optional: Enables lineno mode, but only if one_column mode is also true
#lineno: true

# Optional: Enable one-sided layout, default is two-sided
#one_sided: true

# Optional: Enable section numbering, default is unnumbered
#numbersections: true

# Optional: Specify the depth of section number, default is 5
#secnumdepth: 5

# Optional: Skip inserting final break between acknowledgements, default is false
skip_final_break: true

# Optional: Bibliography 
bibliography: pinp

# Optional: Enable a 'Draft' watermark on the document
#watermark: true

# Customize footer, eg by referencing the vignette
footer_contents: "Parámo La Rusia"

# Produce a pinp document
output: pinp::pinp

# Required: Vignette metadata for inclusion in a package.
vignette: >
  %\VignetteIndexEntry{YourPackage-vignetteentry}
  %\VignetteKeywords{YourPackage, r, anotherkeyword}
  %\VignettePackage{YourPackage}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE, 
                      message = FALSE)

library(readxl)
library(tidyverse)
```

# Introducción

```{r, fig.cap= "Tendencia Diaría de precipitación"}
data<- read_xlsx("Clima Páramo.xlsx")

data<- data %>% mutate(Mes= as.factor(Mes), 
                       Dia= as.factor(Dia))
prep<- data %>% group_by(Mes, Dia) %>% 
  summarise(S_prep= sum(`Preci (mm)`))
  

ggplot(prep , mapping = aes(x= Mes, y= S_prep)) +
  geom_col(mapping = aes(fill= Dia)) #Tendencia diaria

```


```{r, fig.cap= "Tendencia Diaría de precipitación"}
ggplot(prep,mapping = aes(S_prep)) +
  geom_density(mapping = aes(color= Mes)) +
  facet_wrap(~Mes) #tendencia diaria
```


<!--- Analisis de Temperatura --->

```{r, fig.cap= "Tendencia de la temperatura mensual"}

Temp<- data %>% group_by(Mes, Dia) %>% 
  summarise(S_temp= mean(`Temp (grados C)`))

ggplot(Temp, mapping = aes(x= Mes, y= S_temp)) +
  geom_jitter() +
  geom_abline(slope = 0, intercept = mean(data$`Temp (grados C)`), color= "blue")

ggplot(Temp, mapping = aes(S_temp))+
  geom_density(mapping = aes(color= Mes))

```


```{r, fig.cap= "Temperatura media general"}
ggplot(Temp, mapping = aes(x= Dia, y= S_temp)) +
  geom_jitter(mapping = aes(color= Mes)) + facet_wrap(~Mes) + 
  scale_x_discrete(breaks = c(seq(1, 31, 3))) +
  geom_abline(slope = 0, intercept = mean(data$`Temp (grados C)`), color= "blue")
```


<!--- Analisis de Humedad relativa  --->

```{r}
Hr<- data %>% group_by(Mes, Dia) %>% 
  summarise(Hr_p= mean(`Hume Rel (%)`))

ggplot(Hr, mapping = aes(x= Mes, y= Hr_p)) +
  geom_jitter() +
  geom_abline(slope = 0, intercept = mean(data$`Hume Rel (%)`), color= "blue")

```

```{r}
ggplot(Hr, mapping = aes(Hr_p))+
  geom_density(mapping = aes(color= Mes))

```


```{r}
ggplot(Hr, mapping = aes(x= Dia, y= Hr_p)) +
  geom_jitter(mapping = aes(color= Mes)) + facet_wrap(~Mes) + 
  scale_x_discrete(breaks = c(seq(1, 31, 3))) +
  geom_abline(slope = 0, intercept = mean(data$`Hume Rel (%)`), color= "blue")
```

<!--- Analisis de velocidad del viento--->

```{r}

Vw<- data %>% group_by(Mes, Dia) %>% 
  summarise(Vw_p= mean(`Dir viento(gr)`))

ggplot(Vw, mapping = aes(x= Mes, y= Vw_p)) +
  geom_jitter() +
  geom_abline(slope = 0, intercept = mean(Vw$Vw_p), color= "blue")

```


```{r}
ggplot(Vw, mapping = aes(Vw_p))+
  geom_density(mapping = aes(color= Mes))
```


# Materiales y métodos

## Localización y descripción del área de estudio

### 1) Levantamiento de información

### 2) Procesamiento de los datos recolectados

# Resultados y Discusión 

# Conclusiones




