---
title: "Prueba para impresión"
author: "Cristian Gañan"
date: "2/3/2020"
output: 
  pdf_document:
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE)

library(readxl)
library(tidyverse)
library(ggplot2)
```


```{r}
data<- read_xlsx("manual_est_2019_curso.xlsx")

data<- data %>% mutate(Region= as.factor(Region), 
                       ID_Comglomerado= as.factor(ID_Comglomerado),
                       N_SPF= as.factor(N_SPF)) %>% 
  mutate(altura= Dst_2*(tan(Vmas_2*pi/180) - tan(Vmenos_2*pi/180)))

```


## Modelo lineal

```{r}
modelo<- lm(altura ~ DAP_analisis, data)


# table
m<- "$H= 8.822+0.340*DAP$"
tabla<- tibble(Modelo= m,Fc= broom::glance(modelo)$statistic, 
               valor.p= broom::glance(modelo)$p.value, 
               Shapiro= shapiro.test(resid(modelo))[2],
               R.squared= broom::glance(modelo)$r.squared,
               AIC= broom::glance(modelo)$AIC,
               RSE= broom::glance(modelo)$sigma)


```


```{r}
modelo<- lm(altura ~ DAP_analisis + I(DAP_analisis^2), data)


tabla2<- tibble(Modelo= "$H= 6.156+0.561*DAP-0.0032*DAP^2$", 
                Fc= broom::glance(modelo)$statistic, 
                valor.p= broom::glance(modelo)$p.value, 
                Shapiro= shapiro.test(resid(modelo))[2],
                R.squared= broom::glance(modelo)$r.squared,
                AIC= broom::glance(modelo)$AIC,
                RSE= broom::glance(modelo)$sigma)

```


```{r, results='asis', fig.align='center'}
rbind(tabla, tabla2)

```




