---
title: "Resultados"
author: "Cristian Gañan"
date: "23/3/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE, 
                      message = FALSE)
```

```{r}
library(tidyverse)
library(readxl)
library(BIOMASS)

data<- read_xlsx("parcelas (2).xlsx")

data<- data %>% mutate(Habito= as.factor(Habito), Especie= as.factor(Especie), 
                       Parcela= as.factor(Parcela))

data<- data %>% filter(DAP..cm. != 0 & Altura != 0) 
data<- data %>% filter(Altura < 50)

data<- data %>% filter(Especie != "Xylopia frutescens")

data<- data %>% mutate(Habito= if_else(DAP..cm. < 5, "Brinzales", 
                                       if_else(DAP..cm. >10, "Fustales", "Latizales")))
```

# Modelo Weibull

```{r, eval=FALSE, include=FALSE}
model<- modelHD(data$DAP..cm., data$Altura, method = "weibull")

model<- nls(Altura ~ a*(1-exp(-(DAP..cm./b)^c)), data = data,
            start = list(a= 13.324489 , b= 7.134244, c= 1.334295))

ggplot(data, mapping = aes(x= DAP..cm., y= Altura)) +
  geom_point(aes(color= Especie, shape= Habito)) +
  geom_smooth(broom::augment(model), mapping = aes(x= DAP..cm., y= .fitted))
```

# Modelo Michaelis Menten

```{r, fig.cap= "Especie parcela"}
MP<- nls(Altura ~ SSmicmen(DAP..cm., a,b), data = data)

model<- nls(Altura ~ (a*DAP..cm.)/(b+DAP..cm.), data= data,
            start = list(a= 19.803, b= 9.417))

ggplot(data, mapping = aes(x= DAP..cm., y= Altura)) +
  geom_point(aes(color= Parcela, shape= Especie)) +
  geom_smooth(broom::augment(model), mapping = aes(x= DAP..cm., y= .fitted))
```

```{r, fig.cap= "Especie Habito"}
ggplot(data, mapping = aes(x= DAP..cm., y= Altura)) +
  geom_point(aes(color= Especie, shape= Habito)) +
  geom_smooth(broom::augment(model), mapping = aes(x= DAP..cm., y= .fitted))
```


```{r}
knitr::kable(data %>% group_by(Habito) %>% summarise(Dcm= sqrt(mean(DAP..cm.^2))), 
             format = "latex", caption = "Diamtro cuadratico medio")
```


```{r}
data1<- data %>% group_by(Parcela, Habito) %>%  filter(Especie == "\r\nJacaranda Copaia") %>% 
  mutate(`Jacaranda Copaia`= if_else(Parcela == "1" & 
                                          Habito == "Brinzales", 
                                        length(Habito)*10000/50, 
                                        if_else(Parcela == "1" & 
                                                  Habito == "Latizales", 
                                                length(Habito)* 10000/250, 
                                                if_else(Parcela == "1" &
                                                          Habito == "Latizales", 
                                                        length(Habito)*10000/500, 
                                                        if_else(Parcela == "2", 
                                                                length(Habito)*(18*18), 
                                                                if_else(Parcela== "3", 
                                                                        length(Habito)*(30*15), 
                                                                        length(Habito)*(40*20))))))) %>% 
  summarise(`Jacaranda Copaia (ind)`= unique(`Jacaranda Copaia`))
  
data2<- data %>% group_by(Parcela, Habito) %>% filter(Especie == "Vismia macrophylla")  %>% 
  mutate(`Vismia macrophylla` = if_else(Parcela == "1" & 
                                          Habito == "Brinzales", 
                                        length(Habito)*10000/50, 
                                        if_else(Parcela == "1" & 
                                                  Habito == "Latizales", 
                                                length(Habito)* 10000/250, 
                                                if_else(Parcela == "1" & 
                                                          Habito == "Latizales", 
                                                        length(Habito)*10000/500, 
                                                        if_else(Parcela == "2", 
                                                                length(Habito)*(18*18), 
                                                                if_else(Parcela== "3", 
                                                                        length(Habito)*(30*15), 
                                                                        length(Habito)*(40*20))))))) %>% 
  summarise(`Vismia macrophylla (ind)`= unique(`Vismia macrophylla`))

```




```{r}
knitr::kable(data1, format = "latex", caption = "Numero de individuos por hectarea de Jacaranda Copaia")
```

```{r}
knitr::kable(data2, format = "latex", caption = "Numero de individuos por hectarea de Vismia macrophylla")
```

