---
title: Bare Demo of IEEEtran.cls for IEEE Conferences
affiliation:
  institution-columnar: true  

  institution:
    - name: Universidad Nacional de Colombia
      department: Departamento de Ciencias Forestales
      location: Medelín, Antioquia
      email: ccganant@unal.edu.co
      mark: 1
      author:
        - name: Cristian Camilo Gañan
    - name: Universidad Nacional de Colombia
      department: Departamento de Ciencias Forestales
      location: Medellín, Antioquia
      email: cacruzs@unal.edu.co
      mark: 2
      author:
        - name: Camilo Andres Cruz Sanchez
    - name: Universidad Nacional de Colombia
      department: Departamento de Ciencias Forestales
      location: Medellín, Antioquia
      mark: 3
      author:
        - name: Juan Pablo Caicedo Garcia
          email: jpcaicedog@unal.edu.co

keywords: ["keyword 1", "keyword 2"]
abstract: |
  The abstract goes here.
  On multiple lines eventually.

bibliography: mybibfile.bib
output: rticles::ieee_article
#citation_sorting: none   ## used as sorting option of the biblatex package (if selected)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

library(tidyverse)
library(readxl)
library(BiodiversityR)
library(BIOMASS)
library(modelr)

source("distri.R")
```

# Introducción


# Métodos

# Resultados y discusión

```{r}
data<- rbind(read_xls("Grupo2.xls", sheet = "62"), 
             read_xls("Grupo2.xls", sheet = "69"), 
             read_xls("Grupo2.xls", sheet = "70"))

data<- data %>% mutate(Parcela= as.factor(Parcela), 
                       `No. Arbol`= as.factor(`No. Arbol`), 
                       Especie= as.factor(Especie))
```

<!--- Shannon, Simpson and Fisher alpha and Margalef--->

```{r}

tab<- data %>% group_by(Parcela) %>% 
  summarise(Margalef= (length(unique(Especie))-1)/log(NROW(Especie)))

index<- data %>% group_by(Parcela, Especie) %>% 
  summarise(sp= length(Especie)) %>% 
  spread(Especie, sp) %>% 
  mutate_all(funs(replace(., is.na(.), 0)))

sha<- as.tibble(index) %>% select(-c(Parcela)) %>% 
  diversity(., index = "shannon")

sim<- as.tibble(index) %>% select(-c(Parcela)) %>% 
  diversity(., index = "simpson")

z<- as.tibble(index) %>% filter(Parcela == "69")%>% select(-c(Parcela)) %>% 
  fisher.alpha(.) 

x<- z*(log(1+100/z))

z<- as.tibble(index) %>% filter(Parcela == "70")%>% select(-c(Parcela)) %>% 
  fisher.alpha(.)

x2<- z*(log(1+100/z))
x3<- 0.3634532*(log(1+100/0.3634532))

knitr::kable(cbind(tab, tibble(Shannon= sha, Simpson= sim, Fisher= c(x3, x,x2))), format = "latex", caption = "indices alfa")
```

<!--- Diversidad Beta--->

```{r}

#Morhsita
index<- gather(index, "Spp", "N", -Parcela)

spread(index, Parcela, N) %>% mutate(sp1= `62`*`69`, 
                                     sp2= `62`*`70`, 
                                     sp3= `70`*`69`, 
                                     s1= `62`^2, 
                                     s2= `69`^2, 
                                     s3= `70`^2) %>% 
  mutate(sp1c= s1/sum(s1),
         sp2c= s2/sum(s2), 
         sp3c= s3/sum(s3)) %>% 
  summarise(`62-69`= 2*sum(sp1)/((sum(sp1c)+sum(sp2c))*sum(s1)*sum(s2)), 
            `62-70`= 2*sum(sp1)/((sum(sp1c)+sum(sp3c))*sum(s1)*sum(s3)), 
            `69-70`= 2*sum(sp3)/((sum(sp2c)+sum(sp3c))*sum(s2)*sum(s3)))

#Sorensen

index<- data %>% group_by(Parcela, Especie) %>% 
  summarise(sp= length(Especie)) %>% 
  spread(Especie, sp) %>% 
  mutate_all(funs(replace(., is.na(.), 0)))

1-(as.tibble(index) %>% select(-c(Parcela)) %>% vegdist(., binary = TRUE))




```

<!--- Especies esperadas --->

```{r}
#Jacknife
index<- gather(index, "Spp", "N", -Parcela)

#spread(index, Parcela, N) %>% mutate(k= `62`+ `69` + `70`)


#numero de spp esperadas

9+((3-1)/3)*7


# Rarefacción

index<- index %>% group_by(Spp) %>% summarise(n= sum(N)) %>% spread(Spp, n)



rpt<-rarefy(index, seq(0,31, 2), se= T)

curve.tot<- tibble(index = seq(0,31, 2), sp = rpt[1,],sd = rpt[2,])

ggplot(curve.tot, aes(index, sp)) + 
  geom_errorbar(aes(ymax = sp+sd,ymin = sp-sd), col = "red") +
  geom_line(col= "blue") + geom_point() +
  ggtitle("Rarefaccion") + ylab("Numero de especies") +
  xlab("Individuos") +
  theme(plot.title = element_text(size = 15, face="bold"),
        axis.title.x = element_text(face = "bold", size = 13),
        axis.title.y = element_text(face = "bold",size = 13))

```


<!--- IVI ---->

```{r}
knitr::kable(data %>%group_by(Especie, Parcela) %>% mutate(AB= pi/4*(Diametro/100)^2) %>% 
  summarise(FA= length(unique(Especie)), 
            DR= sum(AB), 
            AR= length(Especie)) %>%
  group_by(Especie) %>% 
  summarise(FA= length(Especie),
            DR= sum(DR),
            AR= sum(AR)) %>% 
  mutate(FR= (FA/sum(FA))*100, 
         DR= (DR/sum(DR))*100, 
         AR= (AR/sum(AR))*100) %>% 
  mutate(IVI= DR+AR+FR) %>% select(-c(FA)) %>% 
    arrange(IVI), format = "latex", caption = "IVI")
  

```


<!--- Numero de spp efectivas--->




<!--- Modelos Diametros ---->

```{r}
# Parecla 62

x<- data %>% filter(Parcela == "62")
a<- hist(x$Diametro, breaks = seq(0,15,1.5))
datam<- as.tibble(cbind(Clase= a$breaks, Count= a$counts))

datam %>% summarise(Gamma= adjust(Clas = Clase, Count = Count, distr = "Gamma", interval = 1.5)[2], 
                    Beta= adjust(Clas = Clase, Count = Count, distr = "Beta", interval = 1.5)[2], 
                    Lognormal= adjust(Clas = Clase, Count = Count, distr = "Lognormal", interval = 1.5)[2], 
                    Weibull= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[2], 
                    Chitab= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[1])

bn.d<-data.frame(d=c(rep(0,0),rep(1.5,1),rep(3,0),rep(4.5,24),rep(6,18),
rep(7.5,25), rep(9,9), rep(10.5,7),rep(12,3), rep(13.5,2), rep(15, 0)))

est<- MASS::fitdistr(bn.d$d, "gamma")

data %>% filter(Parcela == "62") %>% ggplot(., mapping = aes(x= Diametro, y= ..density..)) +
  geom_histogram(binwidth = 1.5, mapping = aes(col= "red")) + geom_smooth(mapping = aes(x= Diametro, y= dgamma(Diametro, shape = est$estimate[1], rate = est$estimate[2])), se= FALSE) + facet_wrap(~Parcela)+
  scale_x_continuous(breaks = seq(0,14,1.5))


```



```{r}

x<- data %>% filter(Parcela == "69")
a<- hist(x$Diametro, breaks = seq(0,42,1.5))
datam<- as.tibble(cbind(Clase= a$breaks, Count= a$counts))

datam %>% summarise(Gamma= adjust(Clas = Clase, Count = Count, distr = "Gamma", interval = 1.5)[2], 
                    Beta= adjust(Clas = Clase, Count = Count, distr = "Beta", interval = 1.5)[2], 
                    Lognormal= adjust(Clas = Clase, Count = Count, distr = "Lognormal", interval = 1.5)[2], 
                    Weibull= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[2], 
                    Chitab= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[1])


bn.d<- data.frame(d=c(rep(0,0),rep(1.5,0),rep(3,0),rep(4.5,26),rep(6,11),
rep(7.5,4), rep(9,2), rep(10.5,2),rep(12,5), rep(13.5,3), rep(15, 0), rep(21,2),rep(22.5,2),rep(24,4),rep(25.5,2),rep(27,1),
rep(28.5,0), rep(30,1), rep(31.5,2),rep(33,1), rep(34.5,0), rep(36, 0), rep(37.5, 0), 
rep(39,0), rep(40.5, 1), rep(42,0)))

est<- MASS::fitdistr(bn.d$d, "gamma")

data %>% filter(Parcela == "69") %>% ggplot(., mapping = aes(x= Diametro, y= ..density..)) +
  geom_histogram(binwidth = 1.5, mapping = aes(col= "red")) + geom_smooth(mapping = aes(x= Diametro, y= dgamma(Diametro, shape = est$estimate[1], rate = est$estimate[2])), se= FALSE) + facet_wrap(~Parcela)+
  scale_x_continuous(breaks = seq(0,42,1.5))

```


```{r}

x<- data %>% filter(Parcela == "70")
a<- hist(x$Diametro, breaks = seq(0,27,1.5))
datam<- as.tibble(cbind(Clase= a$breaks, Count= a$counts))

datam %>% summarise(Gamma= adjust(Clas = Clase, Count = Count, distr = "Gamma", interval = 1.5)[2], 
                    Beta= adjust(Clas = Clase, Count = Count, distr = "Beta", interval = 1.5)[2], 
                    Lognormal= adjust(Clas = Clase, Count = Count, distr = "Lognormal", interval = 1.5)[2], 
                    Weibull= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[2], 
                    Chitab= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[1])

bn.d<- data.frame(d=c(rep(0,0),rep(1.5,0),rep(3,0),rep(4.5,4),rep(6,5),
rep(7.5,2), rep(9,4), rep(10.5,1),rep(12,2), rep(13.5,0), rep(15, 2), rep(16.5,2),rep(18,3),rep(19.5,1),rep(21,2),rep(22.5,2),
rep(24,0), rep(25.5,1), rep(27,0)))

est<- MASS::fitdistr(data$Diametro, "gamma")

data %>% filter(Parcela == "70") %>% ggplot(., mapping = aes(x= Diametro, y= ..density..)) +
  geom_histogram(binwidth = 1.5, mapping = aes(col= "red")) + geom_smooth(mapping = aes(x= Diametro, y= dgamma(Diametro, shape = est$estimate[1], rate = est$estimate[2])), se= FALSE) + facet_wrap(~Parcela)+
  scale_x_continuous(breaks = seq(0,42,1.5))
```



<!--- modelos alturas --->

```{r}
x<- data %>% filter(Parcela == "62")
a<- hist(x$Altura, breaks = seq(0,11,1.5))
datam<- as.tibble(cbind(Clase= a$breaks, Count= a$counts))

datam %>% summarise(Gamma= adjust(Clas = Clase, Count = Count, distr = "Gamma", interval = 1.5)[2], 
                    Beta= adjust(Clas = Clase, Count = Count, distr = "Beta", interval = 1.5)[2], 
                    Lognormal= adjust(Clas = Clase, Count = Count, distr = "Lognormal", interval = 1.5)[2], 
                    Weibull= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[2], 
                    Chitab= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[1])

bn.d<-data.frame(d=c(rep(0,0),rep(1.5,2),rep(3,15),rep(4.5,29),rep(6,29),
rep(7.5,9), rep(9,5), rep(10.5,7)))

est<- MASS::fitdistr(bn.d$d, "gamma")

data %>% filter(Parcela == "62") %>% ggplot(., mapping = aes(x= Altura, y= ..density..)) +
  geom_histogram(binwidth = 1.5, mapping = aes(col= "red")) +scale_x_continuous(breaks = seq(0,20,1.5)) + geom_smooth(mapping = aes(x= Altura, y= dgamma(Altura, shape = est$estimate[1], rate = est$estimate[2])), se= FALSE) + facet_wrap(~Parcela)
```


```{r}
x<- data %>% filter(Parcela == "69")
a<- hist(x$Altura, breaks = seq(0,24,1.5))
datam<- as.tibble(cbind(Clase= a$breaks, Count= a$counts))


datam %>% summarise(Gamma= adjust(Clas = Clase, Count = Count, distr = "Gamma", interval = 1.5)[2], 
                    Beta= adjust(Clas = Clase, Count = Count, distr = "Beta", interval = 1.5)[2], 
                    Lognormal= adjust(Clas = Clase, Count = Count, distr = "Lognormal", interval = 1.5)[2], 
                    Weibull= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[2], 
                    Chitab= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[1])


bn.d<- data.frame(d=c(rep(0,0),rep(1.5,0),rep(3,0),rep(4.5,26),rep(6,11),
rep(7.5,4), rep(9,2), rep(10.5,2),rep(12,5), rep(13.5,3), rep(15, 0), rep(21,2),rep(22.5,2),rep(24,4),rep(25.5,2),rep(27,1),
rep(28.5,0), rep(30,1), rep(31.5,2),rep(33,1), rep(34.5,0), rep(36, 0), rep(37.5, 0), 
rep(39,0), rep(40.5, 1), rep(42,0)))

est<- MASS::fitdistr(data$Altura, "gamma")

data %>% filter(Parcela == "69") %>% ggplot(., mapping = aes(x= Altura, y= ..density..)) +
  geom_histogram(binwidth = 1.5, mapping = aes(col= "red")) + scale_x_continuous(breaks = seq(0,23,1.5)) + geom_smooth(mapping = aes(x= Altura, y= dgamma(Altura, shape = est$estimate[1], rate = est$estimate[2])), se= FALSE) + facet_wrap(~Parcela)
```


```{r}
x<- data %>% filter(Parcela == "70")
a<- hist(x$Altura, breaks = seq(0,17,1.5))
datam<- as.tibble(cbind(Clase= a$breaks, Count= a$counts))

datam %>% summarise(Gamma= adjust(Clas = Clase, Count = Count, distr = "Gamma", interval = 1.5)[2], 
                    Beta= adjust(Clas = Clase, Count = Count, distr = "Beta", interval = 1.5)[2], 
                    Lognormal= adjust(Clas = Clase, Count = Count, distr = "Lognormal", interval = 1.5)[2], 
                    Weibull= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[2], 
                    Chitab= adjust(Clas = Clase, Count = Count, distr = "Weibull", interval = 1.5)[1])

bn.d<- data.frame(d=c(rep(0,0),rep(1.5,0),rep(3,0),rep(4.5,4),rep(6,5),
rep(7.5,2), rep(9,4), rep(10.5,1),rep(12,2), rep(13.5,0), rep(15, 2), rep(16.5,2),rep(18,3),rep(19.5,1),rep(21,2),rep(22.5,2),
rep(24,0), rep(25.5,1), rep(27,0)))

est<- MASS::fitdistr(data$Altura, "weibull")

data %>% filter(Parcela == "70") %>% ggplot(., mapping = aes(x= Altura, y= ..density..)) +
  geom_histogram(binwidth = 1.5, mapping = aes(col= "red")) + geom_smooth(mapping = aes(x= Altura, y= dweibull(Altura, shape = est$estimate[1], scale = est$estimate[2])), se= FALSE) + facet_wrap(~Parcela)+
  scale_x_continuous(breaks = seq(0,42,1.5))

```



